apiVersion: v1
kind: Pod
metadata:
  name: my-new-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      ports:
      - containerPort: 80
    - name: redis
      image: redis:6.2.5
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"