services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - PGDATA=/data/postgres
    ports:
      - '5432:5432'
    volumes:
      # - postgres:/data/postgres
      - jobms_local_pgdata:/var/lib/postgresql/data
    networks:
      - microservice-network
#    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user-name@domain-name.com}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-strong-password}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      # - pgadmin:/var/lib/pgadmin
      - jobms_pgadmin-data:/var/lib/pgadmin
    networks:
      - microservice-network
#    restart: unless-stopped

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin-ms
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    environment:
      - HEALTHCHECK_IP=127.0.0.1
    networks:
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-ms
    ports:
      #Default port for Rabbitmq
      - 5672:5672
      #Default port for Rabbitmq management
      - 15672:15672
    networks:
      - microservice-network

  servicereg:
    image: mahansa/servicereg:latest
    container_name: servicereg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network

  gateway-ms:
    image: mahansa/gateway-ms:latest
    ports:
      - 8084:8084
    depends_on:
      - servicereg
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  config-server-ms:
    image: mahansa/config-server-ms:latest
    container_name: config-server-ms
    ports:
      - 8080:8080
    #"depends_on" means that the service will start after what services are listed
    depends_on:
      - servicereg
    networks:
      - microservice-network
    environment:
      #This means application-docker.properties will be picked up instead
      - SPRING_PROFILES_ACTIVE=docker

  companyms:
    image: mahansa/companyms:latest
    container_name: company
    ports:
      - 8081:8081
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # jobms:
  #   image: mahansa/jobms:latest
  #   container_name: job
  #   ports:
  #     - 8082:8082
  #   depends_on:
  #     - servicereg
  #     - config-server-ms
  #   networks:
  #     - microservice-network
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  reviewms:
    image: mahansa/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg
      - config-server-ms
    networks:
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  microservice-network:
    driver: bridge

volumes:
  jobms_local_pgdata:
    external: true
  jobms_pgadmin-data:
    external: true
      